# https://taskfile.dev

version: "3"

vars:
  targetbin: ~/bin
  buildname: concur

tasks:
  default:
    cmds:
      - echo "use 'task -l' to list tasks"
    silent: true
  install:
    desc: copy build file to local bin
    dir: .
    preconditions:
      - test -d {{.targetbin}}/
    cmds:
      - task: build
      - cmd: rm {{.targetbin}}/{{.buildname}}
        ignore_error: true
      - cmd: cp dist/{{.buildname}}_{{OS}}_{{ARCH}}/{{.buildname}} {{.targetbin}}
        ignore_error: true
  build:
    desc: build app
    cmds:
      - goreleaser release --snapshot --rm-dist

  release:
    dir: .
    desc: release to github using goreleaser
    cmds:
      - goreleaser release --rm-dist
  test-image:
    desc: a test of calling concur to copy an image then remove it
    dir: test/image
    cmds:
      - task: install
      # - convert -size 30x30 xc: +noise Random random.png
      # - concur 'convert -size 30x30 xc: +noise Random random{}.png && echo convert' -a '{1..10}'
      - ls -lah
      - concur 'rm -f {1./}{2}.png' -a 'random.png' -a '{1..10}'
      - concur 'cp -p {1} {1./}{2}.png' -a 'random.png' -a '{1..10}'
      - ls -lah
      - concur 'rm {1./}{2}.png' -a 'random.png' -a '{1..10}'
      - ls -lah
